name: timeseries-clustering
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - cmcrameri=1.9=pyhd8ed1ab_1
  - holoviews=1.20.2=py311h06a4308_0
  - matplotlib=3.7.1=py311h38be061_0
  - netcdf4=1.6.2=nompi_py311ha396515_101
  - numpy=1.26.4=py311h64a7726_0
  - pandas=2.2.3=py311h7db5c69_1
  - pip=23.1.2=pyhd8ed1ab_0
  - plotly=5.15.0=py_0
  - pyextremes=2.3.3=pyhd8ed1ab_1
  - python=3.11.8=hab00c5b_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - scikit-learn=1.2.2=py311hc009520_2
  - scikit-learn-extra=0.3.0=py311hd037940_0
  - scipy=1.10.1=py311h64a7726_3
  - seaborn=0.12.2=hd8ed1ab_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tslearn=0.6.3=py311h18e1886_2
  - umap-learn=0.5.7
  - xarray=2023.6.0=pyhd8ed1ab_0
  - pip:
      - jupyterlab==4.2.5
      - keras==3.8.0
      - pycvi-lib==0.1.5
      - tensorboard==2.18.0
      - tensorflow==2.18.0
